### ISSUE TITLE
No module named 'requests'

### ISSUE THREAD

**Issue by andyluo7** [mit-han-lab/TinyChatEngine#55]
amd@ryzen-ai MINGW64 /c/Users/amd/projects/TinyChatEngine/llm
$ python tools/download_model.py --model LLaMA2_7B_chat_awq_int4 --QM QM_x86
Traceback (most recent call last):
  File "C:\Users\amd\projects\TinyChatEngine\llm\tools\download_model.py", line 14, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by RaymondWang0** [comment]
Hi @andyluo7, thank you for your interest in our work. This error shows up due to the missing Python package. We've revised README and added detailed instructions for [the Python environment](https://github.com/mit-han-lab/TinyChatEngine#step-by-step-to-deploy-llama2-7b-chat-with-tinychatengine).
