### ISSUE TITLE
LLaMA2_7B_chat_awq_int4.zip Empty File

### ISSUE THREAD

**Issue by tuobulatuo** [mit-han-lab/TinyChatEngine#64]
Get 106KB of data when downloading model LLaMA2_7B_chat_awq_int4.

**Output:**

python tools/download_model.py --model LLaMA2_7B_chat_awq_int4 --QM QM_CUDA

Start downloading the model to ./LLaMA2_7B_chat_awq_int4.zip.
106KB [00:00, 1668.05KB/s]

File downloaded successfully: ./LLaMA2_7B_chat_awq_int4.zip
The md5sum of the file does not match the expected md5sum. Expected: d0b1d11e498ac7d0a2e90348e946a7f5, got: 92ec5c6c6fc64012b42d4822a6327fde

**Comment by Rkyzzy** [comment]
Hi I met the same issue, it seems that the LLaMA2_7B_chat_awq_int4 QM_CUDA version model's files are missing, did you solve the problem? Or can the author @meenchen check the availability of this model, much thanks!

**Comment by RaymondWang0** [comment]
Hi @tuobulatuo @Rkyzzy, our apologies about the missing file. Something went wrong in our Dropbox. The problem should be fixed now, so I'll close this issue. Please try it again. Feel free to reopen it if you have any further questions. Thanks!
