### ISSUE TITLE
MetalGPU branch not buildable?

### ISSUE THREAD

**Issue by CoryXie** [mit-han-lab/TinyChatEngine#93]
The MetalGPU branch seems not buildable...had to fix around for some issues to pass build.
[0001-Try-to-build-MetalGPU-branch.patch](https://github.com/mit-han-lab/TinyChatEngine/files/14240539/0001-Try-to-build-MetalGPU-branch.patch)

**Comment by CoryXie** [comment]
Reading the metal-cpp document it seems we only need to define the following in one of the cpp files...with that further change I could pass build.

```
#define NS_PRIVATE_IMPLEMENTATION
#define CA_PRIVATE_IMPLEMENTATION
#define MTL_PRIVATE_IMPLEMENTATION
```

**Comment by DerrickYLJ** [comment]
Hello Cory, thanks for your question. The MetalGPU branch is currently in progress and will be available soon.
